### ISSUE TITLE
Enable SSL support

### ISSUE THREAD

**Issue by colinmcfadden** [l3gacyb3ta/theforgecomingsoon#4]
Enable SSL support for warm fuzzy feeling and better SEO

https://vercel.com/blog/automatic-ssl-with-vercel-lets-encrypt

**Comment by l3gacyb3ta** [comment]
![image](https://user-images.githubusercontent.com/58434499/120118334-07fd6400-c160-11eb-9605-5d461be95893.png)
Looks like it's working!
